apiVersion: v1
kind: Pod
metadata:
  labels:
    app: chrony
  name: chrony
spec:
  containers:
  - image: localhost/ntp_server:latest
    name: chrony
    securityContext:
      capabilities:
        add:
        - CAP_SYS_NICE
        - CAP_SYS_RESOURCE
        - CAP_SYS_TIME
  hostNetwork: true
  hostname: lb
